apiVersion: v1
kind: Deployment
metadata:
  name: poc-consumer-go
spec:
  selector:
    matchLabels:
      app: poc-consumer-go
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: poc-consumer-go
    spec:
      containers:
        - name: poc-consumer-go
          image: github.com/dsperax/poc-consumer-go
          imagePullPolicy: IfNotPresent
          ports:
            - name: rest-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/ping
              port: rest-port
            initialDelaySeconds: 1
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/ping
              port: rest-port
            initialDelaySeconds: 1
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: poc-consumer-go
          resources:
            requests:
              cpu: 100m
              memory: 25Mi
            limits:
              cpu: 125m
              memory: 35Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        app: cargadireta
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
