apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: poc-consumer-go
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-consumer-go
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
